mod.mc_title=26.3.x
mod.mc_targets=>=26.3 <26.4
mod.java_version=25
dep.minecraft.fabric=26.3
dep.minecraft.neoforge=26.3
dep.fabric_loader=0.19.5
dep.fabric_api_version=0.161.0+26.3
dep.modmenu_version=21.0.0-beta.1
dep.neoforge_loader=26.3.0.13-beta
dep.neoforge_loader_range=[2,)
dep.neoforge_version_range=[26,)